### ISSUE TITLE
Analyze User data

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/2024-nsf-pose#20]
This task is exploratory to get poc's for the different types of analyses. 

We will need o use these numbers (and may plots) in the doc to show Things like (past) Growth, and health metrics, etc 

# Sub-tasks

- [x] - [x] Send @JacKaL37  user data visualization code examples [#20](https://github.com/freemocap/2024-nsf-pose/issues/20)

- [x] Point @paulmatthis  and @JacKaL37  towards the relevant part of the outline

- [ ] Finish proof of concept code for these analyses/figures:
    - [x] Cumulative pings over time
    - [x] Cumulative unique IPs over time
    - [ ] Global ping map/heatmap (choropleth map) - Ping Lat/Long as dottos on a global map, overlay on heatmap/density  showing density (Bonus: Contour lines in heatmap) 
    - [ ] (e.g.) New users per week
    - [ ] (e.g.) Number of 1-ping users per week (i.e. bouncers)

**Comment by jonmatthis** [comment]
@JacKaL37 - Here's a Google Collab notebook @trentwirth put together a while back to look at User data: https://colab.research.google.com/drive/1Tgaz1RKk-u1n8M8GgbGV3GeA2suBgATl?usp=sharing

I shared access with your `freemocap.org` email

**Comment by jonmatthis** [comment]
@paulmatthis - here's the most relevant section in the current outline: 

https://github.com/freemocap/2024-nsf-pose/blob/main/notes/document-notes/2024-freemocap-nsf-pose-outline.md#sustainability

**Comment by JacKaL37** [comment]
## notes from data chat with @jonmatthis (august 8thish)

Enhancing the user model:
- preliminary user login data (gdrive)
  - choropleth heatmap
  - cumulative unique users
  - new users per week, single-ping-users per week (intelligent bins)
  - polish plots to shininess
- preliminary AI classroom data (mongodb)
- establish future of user model
  - summaries
  - tag extraction
  - user trajectories
  - milestone establishment (and criteria for success)
- Plateaus, Dips, and Leaps (cite me!)
  - instead of dips, we slips?
- establish problems to solve
  - onboarding problems
  - mentorship availability

**Comment by jonmatthis** [comment]
Updated google sheet to have up-to-date geo data for each ip - @JacKaL37 grabbed that version and will not look back
