### ISSUE TITLE
✅ Overall Submission Checklist ✅

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/2024-nsf-pose#6]
# Overall Submission Checklist

from [PAPPG](/docs/notes/nsf_proposal_and_award_policies_and_procedures_guide.pdf) Exhibit II-1 (Page 101 II-63)

- [ ]  General:
  - [x] The proposer has an active and valid SAM registration and a valid UEI.
  - [x] The proposer is eligible to submit a proposal to NSF or meets the eligibility requirements  specified in the applicable solicitation. [link](https://www.nsf.gov/funding/opportunities/pose-pathways-enable-open-source-ecosystems/nsf24-606/solicitation#elig)
  - [ ] The proposer has reviewed and certified compliance with the government-wide financial assistance certifications and representations in SAM.
  - [ ] The proposal is compliant with the requirements specified in the PAPPG and/or the relevant program solicitation.
  - [ ] The proposal is responsive to the relevant program description, announcement, solicitation, or Dear Colleague Letter (if applicable).
  - [ ] If the proposal has been previously declined and is being resubmitted, the proposal has been substantively revised to take into account the major comments from the prior NSF review.
  - [ ] The proposed work is appropriate for funding by NSF, and is not a duplicate of, or substantially similar to, a proposal already under consideration by NSF from the same submitter.
  - [ ] The proposal will be submitted by 5 p.m. submitting organization’s local time if there is an    established deadline date.

---

- [ ]  Single Copy Documents
  - [ ] Authorization to Deviate from NSF Proposal Preparation Requirements is included (if applicable).
  - [ ] List of Suggested Reviewers, or List of Reviewers Not To Include has been provided (optional).
  - [ ] Proposers that require a reasonable and/or accessibility accommodation have contacted the applicable NSF office.
  - [ ] SF LLL, Disclosure of Lobbying Activities has been provided (if applicable)

---

- [ ]  Cover Sheet:
  - [ ] For interdisciplinary proposals, all relevant programs have been identified.
  - [ ] Proposal title includes any necessary prefix.
  - [ ] For a renewal proposal, the previous award number has been entered.
  - [ ] Related letter of intent number has been entered (if applicable).
  - [ ] Related preliminary proposal number has been entered (if applicable).
  - [ ] The “Special Exception to the Deadline Date Policy” box has been checked on the NSF Cover Sheet and the requisite Single Copy Document has been provided (if applicable).
  - [ ] Appropriate box(es) have been checked, and requisite information (if applicable) has been provided.
  - [ ] If the box for “Funding of an International Branch Campus of a U.S. IHE” or “Funding of a Foreign Organization or Foreign Individual” has been checked on the Cover Sheet, the name of the applicable country(ies) in the International Activities Country Name(s) box(es) has been provided.

---

- [ ]  Project Summary:
  - [ ] The Project Summary does not exceed one page.
  - [ ] The Project Summary contains an overview, a statement on the intellectual merit of the proposed activity, and a statement on the broader impacts of the proposed activity.

---

- [ ]  Project Description:
  - [ ] Project Description does not exceed the 15-page limitation specified in the PAPPG or the relevant program solicitation, or the limitation provided in the instructions for types of  proposals (e.g., Planning, RAPID, EAGER and Ideas Lab).
  - [ ] Project Description contains a separate section labeled “Broader Impacts”. The “Broader  Impacts” section header appears on its own line.
  - [ ] Project Description contains the requisite explanation/justification for proposals that includefunding to an International Branch Campus of a U.S. IHE or to a foreign organization or foreign individual, including through use of a subaward or consultant arrangement.
  - [ ] Project Description is self-contained, and Uniform Resource Locators (URLs) have not  been included.

- [ ]  References Cited:
  - [ ] This section includes bibliographic citations only and does not provide parenthetical information outside of the Project Description.
  - [ ] Each reference is in the required format, which may vary according to the norms of the  scientific discipline.

---

- [ ]  Proposal Budget:
  - [ ] Each budget line item has been documented and justified in the Budget Justification.
  - [ ] Any compensation for a senior/key person in excess of two months has been disclosed in the Proposal Budget and justified in the Budget Justification.
  - [ ] Contracts for the purpose of obtaining goods and services for the proposer’s own use have been identified on Line G6 of the Proposal Budget, when applicable.
  - [ ] The amount for indirect costs was calculated by applying the current negotiated indirect cost rate(s) to the approved base(s), and the amount has been specified in the BudgetJustification.
  - [ ] Each Budget Justification does not exceed five pages or the page limitation specified in   the relevant program solicitation. For proposals that contain subawards, each subaward   includes a separate Budget Justification that does not exceed five pages.

---

- [ ]  Facilities, Equipment and Other Resources:
  - [ ] An aggregated description of the internal and external resources (both physical and personnel) that the organization and its collaborators will provide to the project, should it be funded, has been included.
  - [ ] In-kind contributions intended for use on the project being proposed (such as office/laboratory space, equipment, supplies, employees, students) have been identified, where applicable.
  - [ ] No quantifiable financial information has been provided.
  - [ ] If there are no facilities, equipment or other resources identified, a statement to that effect has been included in this section of the proposal and uploaded into Research.gov or Grants.gov.

---

- [ ]  Senior/Key Personnel Documents
  - [ ]  Biographical Sketch(es):
    - [ ] A separate Biographical Sketch has been prepared through use of SciENcv and provided for each individual identified as a senior/key person on the project.
    - [ ] The content described has been prepared in accordance with the instructions and does not contain additional information beyond that specified. Note that there is no longer a page limitation to this section of the proposal.

- [ ]  Current and Pending (Other) Support:
  - [ ] A separate Current and Pending (Other) Support document has been prepared throughuse of SciENcv and provided for each individual identified as a senior/key person on theproject. Each pdf file has been uploaded into Research.gov or Grants.gov.
  - [ ] The content described has been prepared in accordance with the instructions and does not contain additional information beyond that specified.
  - [ ] 
  - [ ] Collaborators and Other Affiliations (COA):

---

- [ ]  Special Information and Supplementary Documentation:
  - [ ] A Mentoring Plan (that covers both postdoctoral researchers and graduate students supported on the project), limited to one page, has been included, if required.
  - [ ] A Data Management and Sharing Plan, limited to two pages, has been included.
  - [ ] Letters of collaboration documenting collaborative arrangements of significance to the proposal have been included, if applicable.
  - [ ] Other types of information identified in Chapter II.D.2.i have been included, as appropriate.
  - [ ] Any additional items specified in a relevant program solicitation have been included.

---

- [ ]  Appendices:
  - [ ] Appendices have not been included unless a deviation has been authorized.

---

- [ ]  Other Types of Proposals:
  - [ ] For other types of proposals (see Chapter II.F), the applicable proposal preparation  guidance has been followed.

---

- [ ]  Other Reminders:
  - [ ] If the proposal contains off-campus or off-site research, a plan has been developed for that proposal prior to proposal submission. The plan is not submitted to NSF for review but is maintained in the organizational records (see Chapter II.E.9).
  - [ ] An individual development plan has been developed for each postdoctoral scholar and graduate student who would be receiving substantial support from an NSF award. These plans are not submitted to NSF for review but are maintained in the organizational records (see Chapter VII.B.7).
  - [ ] Prior written approval from the official(s) designated by the relevant Tribal Nation(s) has been obtained for any proposal that may impact the resources or interests of a federal recognized American Indian or Alaska Native Tribal Nation (see Chapter II.E.10).
