### ISSUE TITLE
Project Description

### ISSUE THREAD

**Issue by jonmatthis** [freemocap/2024-nsf-pose#7]
[document\project-description\project-description.tex](https://github.com/jonmatthis/2024-nsf-pose/blob/main/document/project-description/project-description.tex)

## Tasks
- [x] #12
- [ ] #14 
 
## Subsections: 
- [ ] Establishing FMC-C growth (point: we got a lot of users) #20 
- [ ] Describing Metrics/Health checks for FMC-C #20 
- [ ] Whackadoo AI plans (Skellybot) - AI-simulacrum based pseudo-mentorship (and User Model/trajectory shaping) #25
